### ISSUE TITLE
error on arithmetic expression 

### ISSUE THREAD

**Issue by usernameeeeeeeeeeeee** [gems-uff/noworkflow#126] opened 2020-04-07 13:18 UTC
When I running the following program in noworkflow, 
```
x = 1
x = x + 3
print(x)
```
I get the following errors
```
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/dynamic.py:48: SAWarning: On relationship Trial.code_blocks, 'dynamic' loaders cannot be used with many-to-one/one-to-one relationships and/or uselist=False.  This warning will be an exception in a future release.
  "future release." % self.parent_property
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 105, in parse
    tree = visitor.visit(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
    return ast.fix_missing_locations(self.process_script(node, cls))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 143, in process_script
    new_node.body, self.container_id, index
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 198, in process_body
    self.visit_assign(new_body, stmt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 496, in visit_assign
    [activation(), self.capture(node.value, mode="assign")]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 1179, in capture
    return dependency_rewriter.visit(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_expr.py", line 172, in visit_BinOp
    op_id = self.rewriter.create_ast_component(node.op_pos, "operator")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 63, in create_ast_component
    node.name = pyposast.extract_code(self.lcode, node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyposast/visitor.py", line 44, in extract_code
    first_line, first_col = node.first_line - 1, node.first_col
AttributeError: 'list' object has no attribute 'first_line'
[now] AttributeError("'list' object has no attribute 'first_line'")
the execution finished with an uncaught exception. Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_execution/execution.py", line 54, in collect_provenance
    metascript.code, metascript.path, "exec"
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 138, in compile
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 125, in collect
    source, filename, mode
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/utils/metaprofiler.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 114, in parse
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 105, in parse
    tree = visitor.visit(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
    return ast.fix_missing_locations(self.process_script(node, cls))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 143, in process_script
    new_node.body, self.container_id, index
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 198, in process_body
    self.visit_assign(new_body, stmt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 496, in visit_assign
    [activation(), self.capture(node.value, mode="assign")]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 1179, in capture
    return dependency_rewriter.visit(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_expr.py", line 172, in visit_BinOp
    op_id = self.rewriter.create_ast_component(node.op_pos, "operator")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 63, in create_ast_component
    node.name = pyposast.extract_code(self.lcode, node)
huiyunpengdeMacBook-Air:Desktop huiyunpeng$ now run test2.py
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sqlalchemy/orm/dynamic.py:48: SAWarning: On relationship Trial.code_blocks, 'dynamic' loaders cannot be used with many-to-one/one-to-one relationships and/or uselist=False.  This warning will be an exception in a future release.
  "future release." % self.parent_property
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 105, in parse
    tree = visitor.visit(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
    return ast.fix_missing_locations(self.process_script(node, cls))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 143, in process_script
    new_node.body, self.container_id, index
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 198, in process_body
    self.visit_assign(new_body, stmt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 496, in visit_assign
    [activation(), self.capture(node.value, mode="assign")]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 1179, in capture
    return dependency_rewriter.visit(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_expr.py", line 172, in visit_BinOp
    op_id = self.rewriter.create_ast_component(node.op_pos, "operator")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 63, in create_ast_component
    node.name = pyposast.extract_code(self.lcode, node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyposast/visitor.py", line 44, in extract_code
    first_line, first_col = node.first_line - 1, node.first_col
AttributeError: 'list' object has no attribute 'first_line'
[now] AttributeError("'list' object has no attribute 'first_line'")
the execution finished with an uncaught exception. Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_execution/execution.py", line 54, in collect_provenance
    metascript.code, metascript.path, "exec"
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 138, in compile
    **kwargs
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 125, in collect
    source, filename, mode
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/utils/metaprofiler.py", line 46, in wrapper
    result = func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 114, in parse
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/definition.py", line 105, in parse
    tree = visitor.visit(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 212, in visit_Module
    return ast.fix_missing_locations(self.process_script(node, cls))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 143, in process_script
    new_node.body, self.container_id, index
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 198, in process_body
    self.visit_assign(new_body, stmt)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 496, in visit_assign
    [activation(), self.capture(node.value, mode="assign")]
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 1179, in capture
    return dependency_rewriter.visit(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ast.py", line 262, in visit
    return visitor(node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_expr.py", line 172, in visit_BinOp
    op_id = self.rewriter.create_ast_component(node.op_pos, "operator")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/noworkflow/now/collection/prov_definition/transformer_stmt.py", line 63, in create_ast_component
    node.name = pyposast.extract_code(self.lcode, node)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyposast/visitor.py", line 44, in extract_code
    first_line, first_col = node.first_line - 1, node.first_col
AttributeError: 'list' object has no attribute 'first_line'
```
My python version is 3.7, and noWorkflow 2.0.0-alpha. And I'm running on a Mac.

**Comment by JoaoFelipe** [comment] 2020-04-09 23:05
I couldn't reproduce your error here.
It may be related to PyPosAST. Can you try to update it by running ` pip install --upgrade pyposast`  or tell me which version are you using by looking into `pip freeze`?

Thanks

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-13 12:51
Hi,

I've run pip install --upgrade pyposast, but it shows that
Requirement already up-to-date: pyposast in
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
(1.5.0).

Thanks

**Comment by JoaoFelipe** [comment] 2020-04-14 00:43
What about noworkflow, which version (commit hash) are you running?

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-14 01:57
I'm using noWorkflow 2.0.0-alpha

**Comment by JoaoFelipe** [comment] 2020-04-14 18:48
@linharesh was able to reproduce your issue on a Mac. I'm working with him to fix it.

I suspect an update on SQLAlchemy caused this. Which version are you both running? Did you install it directly on the system or did you use some sort of environment (conda, pyenv, ...)?

**Comment by linharesh** [comment] 2020-04-14 22:01
I was able to find a temporary solution to this problem.
First, open the terminal and uninstall the noworkflow-alpha from your computer
`pip uninstall noworkflow-alpha`
Just to be sure, i suggest you try to uninstall noworkflow:
`pip uninstall noworkflow`
Now, clone noWorkFlow repository
`git clone https://github.com/gems-uff/noworkflow.git`
Get in the noworkflow directory
`cd noworkflow`
Switch to branch 2.0.0-alpha:
`git checkout -b 2.0-alpha`
Get in the capture directory:
`cd capture`
Install noWorkFlow 2.0-alpha with the following command (you must be in noworkflow/capture directory):
`python setup.py install`
After that, noworkflow should be running correctly.
If you find some problem please contact us!

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-16 14:49
I'm using  SQLAlchemy  1.3.13 and I install it directly on the system.

I got this error when running python setup.py install.

error: The 'pyposast>=1.5.0' distribution was not found and is required by
noworkflow


Thanks a lot!

**Comment by linharesh** [comment] 2020-04-16 15:41
Have you tried to install pyposast (1.5.0) from pip?
`pip install pyposast==1.5.0`

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-16 15:49
yes.

Requirement already satisfied: pyposast==1.5.0 in
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
(1.5.0)

**Comment by linharesh** [comment] 2020-04-16 15:58
So pyposast 1.5.0 is installed. 
I suggest you try to check if noworkflow is installed with the following command:
`now --version`
It should be "noWorkflow 2.0.0a0"
If the noworkflow version is displayed correctly, try to run a script with 'now run program.py' where program.py is the name of your script.
If the noworkflow version is not displayed correctly, I suggest you install again with `python setup.py install` inside noworkflow/capture directory.

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-16 16:05
Installed /Library/Python/2.7/site-packages/noworkflow-1.12.0-py2.7.egg

Processing dependencies for noworkflow==1.12.0

Searching for pyposast>=1.5.0

Reading https://pypi.python.org/simple/pyposast/

Best match: PyPosAST 1.5.0

Downloading
https://files.pythonhosted.org/packages/02/c8/3a6b5ff81bb73f97e54e1a4e168349d90f78b5714373a2b4dbc7bc4f1ad6/PyPosAST-1.5.0.tar.gz#sha256=4ccb41cc11fd3b81c8f269d2ce36f683c557bfb612fc116de3974b0bfca49120

Processing PyPosAST-1.5.0.tar.gz

Writing /tmp/easy_install-tp2CrI/PyPosAST-1.5.0/setup.cfg

Running PyPosAST-1.5.0/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-tp2CrI/PyPosAST-1.5.0/egg-dist-tmp-xtEMjN

>>> Please verify the pypandoc installation.

>>> Git Describe Error:

    fatal: not a git repository (or any of the parent directories):
.gitzip_safe flag not set; analyzing archive contents...

Removing /Library/Python/2.7/site-packages/PyPosAST-1+unknown-py2.7.egg

Copying PyPosAST-1+unknown-py2.7.egg to /Library/Python/2.7/site-packages

PyPosAST 1+unknown is already the active version in easy-install.pth


Installed /Library/Python/2.7/site-packages/PyPosAST-1+unknown-py2.7.egg

error: The 'pyposast>=1.5.0' distribution was not found and is required by
noworkflow


*This is what I got when running python setup.py install inside the capture
directory.*

**Comment by linharesh** [comment] 2020-04-16 16:19
"Processing dependencies for noworkflow==1.12.0"
It seems that you are trying to install version 1.12.0, and not 2.0.0.
I am sorry but I misspelled a command in my previous instructions.
Please, remove the current noworkflow repository
`rm -rf noworkflow`
Clone the repository again:
`git clone https://github.com/gems-uff/noworkflow.git`
Get in the noworkflow directory:
`cd noworkflow`
The correct command to switch to branch 2.0.0-alpha (it should NOT contain a "-b", my mistake):
`git checkout 2.0-alpha`
And then:
`cd capture`
`python setup.py install`

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-17 03:47
I got the same error when running these commands. And I've also tried to
run pip install pyposast==1.5.0

Installed /Library/Python/2.7/site-packages/noworkflow-2.0.0a0-py2.7.egg

Processing dependencies for noworkflow==2.0.0a0

Searching for pyposast>=1.5.0

Reading https://pypi.python.org/simple/pyposast/

Best match: PyPosAST 1.5.0

Downloading
https://files.pythonhosted.org/packages/02/c8/3a6b5ff81bb73f97e54e1a4e168349d90f78b5714373a2b4dbc7bc4f1ad6/PyPosAST-1.5.0.tar.gz#sha256=4ccb41cc11fd3b81c8f269d2ce36f683c557bfb612fc116de3974b0bfca49120

Processing PyPosAST-1.5.0.tar.gz

Writing /tmp/easy_install-afqOC0/PyPosAST-1.5.0/setup.cfg

Running PyPosAST-1.5.0/setup.py -q bdist_egg --dist-dir
/tmp/easy_install-afqOC0/PyPosAST-1.5.0/egg-dist-tmp-pxeoAm

>>> Please verify the pypandoc installation.

>>> Git Describe Error:

    fatal: not a git repository (or any of the parent directories):
.gitzip_safe flag not set; analyzing archive contents...

Removing /Library/Python/2.7/site-packages/PyPosAST-1+unknown-py2.7.egg

Copying PyPosAST-1+unknown-py2.7.egg to /Library/Python/2.7/site-packages

PyPosAST 1+unknown is already the active version in easy-install.pth


Installed /Library/Python/2.7/site-packages/PyPosAST-1+unknown-py2.7.egg

error: The 'pyposast>=1.5.0' distribution was not found and is required by
noworkflow

**Comment by JoaoFelipe** [comment] 2020-04-17 05:12
I'm confused. At first, you were using Python 3.7, but the last log has references to 2.7. Maybe your python installations are mixed, so lets try something more explicit:

Uninstall the dependencies:
```
python3 -m pip uninstall noworkflow
python3 -m pip uninstall noworkflow-alpha
python3 -m pip uninstall pyposast
python -m pip uninstall noworkflow
python -m pip uninstall noworkflow-alpha
python -m pip uninstall pyposast
```

Remove the current noworkflow repository:
`rm -rf noworkflow`

Clone the repository again:
`git clone https://github.com/gems-uff/noworkflow.git`

Get in the noworkflow directory:
`cd noworkflow`

Switch to branch 2.0-alpha:
`git checkout 2.0-alpha`

Install noworkflow locally using pip (instead of python setup install)
`python3 -m pip install -e capture` 

If `now run script.py` does not work, try `python3 -m noworkflow run script.py`. If it does not work either, can you tell me the outputs of `which python` and `which now`?

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-17 09:02
Hi I've tried python3 -m noworkflow run script.py . The output is

[now] invalid noWorkflow database

[now] it is probably outdated


The output for which python: /usr/bin/python

The output for which now:
/Library/Frameworks/Python.framework/Versions/3.8/bin/now

**Comment by JoaoFelipe** [comment] 2020-04-17 14:18
Try to remove the database folder:
`rm .noworkflow`
(note the dot)

It was probably created in the previous runs (either noworkflow-alpha from pypi or noworkflow 1.12) and has a different schema

After that, `now run script.py` should work

**Comment by usernameeeeeeeeeeeee** [comment] 2020-04-17 14:24
Yes! It works! Thank you sooooo much!
I hope you are staying well and safe these days!

**Comment by JoaoFelipe** [comment] 2020-04-17 14:36
Great! I will close this issue. Please, open a new one if you find other issues.
I hope you are also staying well and safe.

Thanks again @linharesh for figuring out the issue.

**Closed by JoaoFelipe** 2020-04-17 14:36 UTC
